server:
  port: 0

spring:
  application:
    name: deal-service
  output:
    ansi:
      enabled: always # ?? ?? ??
  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 7MB
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled : true
  sleuth:
    sampler:
      probability: 1.0
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: deal
      profile: prod

logging:
  level:
    com.ssafy.nuguri.dealservice.client: debug
    org.hibernate.SQL: debug
    com.amazonaws.util.EC2MetadataUtils: error

management:
  endpoints:
    web:
      exposure:
        include: "*"