server:
  port: 0

spring:
  application:
    name: member-service
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled : true
  sleuth:
    sampler:
      probability: 1.0


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  redis:
    host: localhost
    port: 6379

logging:
  level:
    nuguri:
      nuguri_member: debug
    org.hibernate.SQL: debug
    com.amazonaws.util.EC2MetadataUtils: error